[package]
name = "runner"
version = "0.3.1"
authors = ["steve donovan <steve.j.donovan@gmail.com>"]
description = "utility for running Rust snippets"

documentation = "https://docs.rs/runner"
repository = "https://github.com/stevedonovan/runner"

readme = "readme.md"

keywords = ["compiler-runner","scripting","snippets"]

license = "MIT"

[dependencies]
easy-shortcuts = "0.3"
lapp = "0.3"
open = "1.2"
lazy_static = "0.2"
semver = "0.9"

[profile.release]
lto = true
panic = 'abort'





